# Generated by Django 4.1.2 on 2022-11-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="despensa",
            name="precio",
            field=models.FloatField(blank=True, db_column="Precio", null=True),
        ),
        migrations.AlterField(
            model_name="vegetales",
            name="precio",
            field=models.FloatField(blank=True, db_column="Precio", null=True),
        ),
    ]
